version: '3.7'

services:
  master:
    build: .
    ports:
     - "8089:8089"
    volumes:
      - ./src:/src
    # command: -f /src/locustfile.py --master
    command: -f /src/locustfile.py --master --timescale --grafana-url=http://192.168.11.1:3030/ --pghost=postgres --pgport=5432 --pgpassword=password --pguser=postgres
  worker:
    build: .
    volumes:
      - ./src:/src
    # command: -f /src/locustfile.py --worker --master-host master
    command: -f /src/locustfile.py --worker --master-host master --timescale --grafana-url=http://192.168.11.1:3030/ --pghost=postgres --pgport=5432 --pgpassword=password --pguser=postgres
    depends_on:
      - master
      - postgres

  postgres:
      image: cyberw/locust-timescale:4
      ports:
        # remove the 127.0.0.1 to expose postgres to other machines (including load gen workers outside this machine)
        - 5432:5432
      environment:
        # change the password if you intend to expose postgres to other machines
        - POSTGRES_PASSWORD=password
        - TIMESCALEDB_TELEMETRY=off
      volumes:
        - postgres_data:/var/lib/postgresql/data
  grafana:
    image: cyberw/locust-grafana:2
    environment:
      # these settings are not particularly safe, dont go exposing Grafana externally without changing this.
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_LOG_LEVEL=warn # reduce log spamming. Remove this if you need to debug grafana.
    ports:
      - 3030:3000
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data: null
  grafana_data: null
