apiVersion: v1
kind: Service
metadata:
  name: super-app-load-balancer
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 3000
      targetPort: 3000
  selector:
    app: super-app
