apiVersion: v1
kind: Service
metadata:
  name: super-app-node-port
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    app: super-app
