apiVersion: apps/v1
kind: Deployment
metadata:
  name: fog-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: fog-app
  replicas: 2
  template:
    metadata:
      labels:
        app: fog-app
    spec:
      containers:
      - name: fog-app
        image: public.ecr.aws/f9w6d5a2/fog-app:latest
        ports:
        - containerPort: 3000
