apiVersion: apps/v1
kind: Deployment
metadata:
  name: fog-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: fog-app
  replicas: 4
  template:
    metadata:
      labels:
        app: fog-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      containers:
      - name: fog-app
        image: public.ecr.aws/f9w6d5a2/fog-app:latest
        ports:
        - containerPort: 3000
