apiVersion: v1
kind: Service
metadata:
  name: fog-app-load-balancer
spec:
  type: LoadBalancer
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 3000
      targetPort: 3000
      nodePort: 30003
  selector:
    app: fog-app
