apiVersion: v1
kind: Service
metadata:
  name: fog-app-service
spec:
  type: NodePort
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 3000
      targetPort: 3000
      nodePort: 30002
  selector:
    app: fog-app
