services:
  super-app:
    container_name: super-app
    build:
      context: ./super-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./super-app:/go/src
    environment:
      MYSQL_DATABASE: super-app
      MYSQL_USER: super-app
      MYSQL_PASSWORD: super-app
      MYSQL_HOST: db
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: super-app
      MYSQL_USER: super-app
      MYSQL_PASSWORD: super-app
  mg-app:
    container_name: mg-app
    build:
      context: ./mg-app
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    volumes:
      - ./mg-app:/go/src
      #- $HOME/.kube/k3s-cluster-a.yaml:/go/src/k3s.yaml
      - $HOME/.kube/k3s-cluster-b.yaml:/go/src/k3s.yaml
      - ./cpu.csv:/go/src/cpu.csv
    environment:
      - ENV=local
    depends_on:
      - mg-app-sub
  mg-app-sub:
    container_name: mg-app-sub
    build:
      context: ./mg-app-sub
      dockerfile: Dockerfile.dev
    volumes:
      - ./mg-app-sub:/go/src/
      - ./cpu.csv:/go/src/cpu.csv
  fog-app:
    container_name: fog-app
    build:
      context: ./fog-app
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    volumes:
      - ./fog-app:/go/src
volumes:
  db-store:
