apiVersion: apps/v1
kind: Deployment
metadata:
  name: mg-app-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: mg-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mg-app
    spec:
      serviceAccountName: mg-app-sa
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: In
                values:
                - 'true'
      containers:
      - name: mg-app
        image: public.ecr.aws/f9w6d5a2/mg-app
        ports:
        - containerPort: 3000
