apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mg-app-rb
subjects:
  - kind: ServiceAccount
    name: mg-app-sa
    namespace: default
roleRef:
  kind: ClusterRole
  name: mg-app-role
  apiGroup: rbac.authorization.k8s.io
