version: '3.3'
services:
  vpn:
    hostname: ec2-node
    container_name: tailscale
    image: tailscale/tailscale:latest
    network_mode: "host"
    tty: true
    volumes:
      - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled
    restart: always

