apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# mg-app
- mg-app/daemon-set.yaml
- mg-app/service-account.yaml
- mg-app/role.yaml
- mg-app/role-binding.yaml
# fog-app
- fog-app/deployment.yaml
- fog-app/load-balancer.yaml

# nginx for debugging
# - nginx/node-port.yaml
# - nginx/deployment.yaml
